---
title: "whitevsnonwhite"
author: "Lauren Henderson"
date: "2024-07-23"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(googlesheets4)
```

```{r data cleaning yay}
library(tidyverse)
library(rsample)
library(glmnet)
library(MASS)
set.seed(3)
setwd('C:/Users/lauri/OneDrive/Documents/COSMOS/healthy-aging-project')

npha_data <- read_csv("data/NPHA-doctor-visits.csv")


npha_data <- npha_data %>%
  mutate(`Phyiscal Health` = case_when(`Phyiscal Health` == 2 ~ 1,
                                       `Phyiscal Health` == 5 ~ 4,
                                       .default = `Phyiscal Health`),
         `Dental Health` = case_when(`Dental Health` == 2 ~ 1,
                                     `Dental Health` == 5 ~ 4,
                                     `Dental Health` == 6 ~ 4,
                                     .default = `Dental Health`))

npha_data <- npha_data %>% 
  filter(`Phyiscal Health` != -1, `Mental Health` != -1, `Dental Health` != -1, `Trouble Sleeping` != -1, `Prescription Sleep Medication` != -1) %>%
  mutate(`Mental Health` = case_when(`Mental Health` == 5 ~3, `Mental Health` ==4 ~3, .default = `Mental Health`)) %>% 
  mutate(Employment = case_when(Employment == 2 ~1, .default = Employment)) %>% 
  mutate(`Trouble Sleeping` = case_when(`Trouble Sleeping` == 2 ~1, .default = `Trouble Sleeping`)) %>% 
  mutate(`Prescription Sleep Medication` = case_when(`Prescription Sleep Medication` == 2 ~1, .default = `Prescription Sleep Medication`)) %>% 
  mutate(Race = case_when(Race != 1 ~ 0, .default = Race)) %>% 
  dplyr::select(-Age)

npha_data <- npha_data %>% 
  mutate(Physical_Health = `Phyiscal Health`,
         Mental_Health = `Mental Health`,
         Dental_Health = `Dental Health`,
         Employment = Employment,
         Trouble_Sleeping = `Trouble Sleeping`,
         Stress_Sleeping = `Stress Keeps Patient from Sleeping`,
         Pain_Sleeping = `Pain Keeps Patient from Sleeping`,
         Bathroom_Sleeping = `Bathroom Needs Keeps Patient from Sleeping`,
         Unknown_Sleeping = `Uknown Keeps Patient from Sleeping`,
         Medication_Sleeping = `Medication Keeps Patient from Sleeping`,
         Prescription_Sleep_Medication = `Prescription Sleep Medication`,
         Race = Race,
         .keep = "unused") %>% 
        mutate_all(as.factor)

```



```{r white}
white <- npha_data %>% 
  filter(Race == 1)




mod <- polr(`Number of Doctors Visited` ~ ., data = white, Hess =TRUE, method = "cloglog")

ctable_white <- coef(summary(mod))
p <- pnorm(abs(ctable_white[,"t value"]), lower.tail = FALSE) * 2
ctable_white <- cbind(ctable_white, "p value" = p)

ctable_white

```


```{r}
nonwhite <- npha_data %>% 
  filter(Race != 1)



mod <- polr(`Number of Doctors Visited` ~ ., data = nonwhite, Hess =TRUE, method = "cloglog")



ctable_nonwhite <- coef(summary(mod))
p <- pnorm(abs(ctable_nonwhite[,"t value"]), lower.tail = FALSE) * 2
ctable_nonwhite <- cbind(ctable_nonwhite, "p value" = p)



filtered_nonwhite <- ctable_nonwhite[,c(1,4)]

filtered_white <- ctable_white[,c(1,4)]

ctable <- cbind(filtered_white, filtered_nonwhite) %>% `colnames<-`(c("White Coef", "White P-Values", "Non-White Coef", "Non-White P-Values")) 

nrow(ctable)
ctable <- apply(ctable, 2, function(x){round(x,digits = 4)})

rownames(ctable) <- c(
  "Retired", "Not_Working", "Female", 
  "Good_Physical_Health", "Poor_Physical_Health", 
  "Good_Mental_Health", "Poor_Mental_Health", 
  "Good_Dental_Health", "Poor_Dental_Health", 
  "No_Trouble_Sleeping", "Stress_Affects_Sleep", 
  "Pain_Affects_Sleep", "Bathroom_Needs_Affect_Sleep", "Unknown_Affects_Sleep",
  "Medication_Affects_Sleep", "No_Prescription_Sleep_Medication", "1|2", "2|3"
)

ctable


```
```{r}
white_coef <- ctable[1:16,1]
white_logodds <- exp(white_coef)
white_logodds_mag <- white_logodds -1



nonwhite_coef <- ctable[1:16,3]
nonwhite_logodds <- exp(nonwhite_coef)
nonwhite_logodds_mag <- nonwhite_logodds-1

logodds_mag_table <- cbind(white_logodds_mag, nonwhite_logodds_mag) %>% `colnames<-`(c("White Logodds Magnitude", "Non-White Logodds Magnitude")) 

logodds_mag_table

```
```{r}

```


# 1|2
```{r}
one_two_adj_white <- ctable[17,1]
base_table <- ctable[1:16,]
base_table[,1] <- base_table[,1] +one_two_adj_white

one_two_adj_nonwhite <- ctable[17,3]

base_table[,3] <- base_table[,3] + one_two_adj_nonwhite

p_val_nonwhite <- ctable[17, 4]

base_table[,4] <- base_table[,4] + p_val_nonwhite

base_table



```

# 2|3
```{r}
two_three_adj_white <- ctable[18,1]
base_table <- ctable[1:16,]
base_table[,1] <- base_table[,1] + two_three_adj_white

two_three_adj_nonwhite <- ctable[18,3]

base_table[,3] <- base_table[,3] + two_three_adj_nonwhite

p_val_white <- ctable[18,2]


base_table[,2] <- base_table[,2] + p_val_white


p_val_nonwhite <- ctable[18, 4]

base_table[,4] <- base_table[,4] + p_val_nonwhite

base_table


```


#whole dataset log odds
```{r}
mod_whole <- polr(`Number of Doctors Visited` ~ ., data = npha_data, Hess =TRUE, method = "cloglog")


coeftable <- coef(summary(mod_whole))
p <- pnorm(abs(coeftable[,"t value"]), lower.tail = FALSE) * 2
coef_table <- cbind(coeftable, "p value" = p)
filtered_coefs <- coef_table[,c(1,4)]



filtered_coefs <- apply(filtered_coefs, 2, function(x){round(x,digits = 4)})



rownames(filtered_coefs) <- c(
  "Retired", "Not_Working", "White", "Female",
  "Good_Physical_Health", "Poor_Physical_Health",
  "Good_Mental_Health", "Poor_Mental_Health",
  "Good_Dental_Health", "Poor_Dental_Health",
  "No_Trouble_Sleeping", "Stress_Affects_Sleep",
  "Pain_Affects_Sleep", "Bathroom_Needs_Affect_Sleep", "Unknown_Affects_Sleep",
  "Medication_Affects_Sleep", "No_Prescription_Sleep_Medication", "1|2", "2|3"
)


logodds <- exp(filtered_coefs[1:16, 1])

logodds_mag <- logodds-1

logodds_mag

```


